package com.PetKing5_480x800;

/* loaded from: classes.dex */
/**
 * The {@code fakeR} class is a placeholder for resource identifiers used in the application.
 * It contains nested static classes representing different types of resources such as arrays,
 * attributes, drawables, IDs, layouts, and strings. Each nested class holds constants that
 * map to the resource IDs generated by the Android build system.
 *
 * <p>Nested Classes:</p>
 * <ul>
 *   <li>{@code array} - Contains resource IDs for arrays.</li>
 *   <li>{@code attr} - Contains resource IDs for attributes.</li>
 *   <li>{@code drawable} - Contains resource IDs for drawable resources.</li>
 *   <li>{@code id} - Contains resource IDs for view IDs.</li>
 *   <li>{@code layout} - Contains resource IDs for layout resources.</li>
 *   <li>{@code string} - Contains resource IDs for string resources.</li>
 * </ul>
 *
 * <p>Example usage:</p>
 * <pre>
 * {@code
 * int iconResId = fakeR.drawable.icon;
 * String appName = getString(fakeR.string.app_name);
 * }
 * </pre>
 */
/**
 * The {@code fakeR} class is a placeholder for resource IDs that are typically generated by the Android build system.
 * This class contains nested static classes representing different types of resources such as arrays, attributes, 
 * drawables, IDs, layouts, and strings. Each nested class contains static final fields that map to resource IDs.
 */
public final class fakeR {

    /**
     * The {@code array} class contains resource IDs for arrays.
     */
    public static final class array {
        /**
         * Resource ID for the FontSize array.
         */
        public static final int FontSize = 0x7f050000;
    }

    /**
     * The {@code attr} class is a placeholder for attribute resources.
     */
    public static final class attr {
    }

    /**
     * The {@code drawable} class contains resource IDs for drawable resources.
     */
    public static final class drawable {
        /**
         * Resource ID for the icon drawable.
         */
        public static final int icon = 0x7f020000;
    }

    /**
     * The {@code id} class contains resource IDs for view IDs.
     */
    public static final class id {
        /**
         * Resource ID for the first button.
         */
        public static final int button1 = 0x7f060000;
        
        /**
         * Resource ID for the second button.
         */
        public static final int button2 = 0x7f060001;
    }

    /**
     * The {@code layout} class contains resource IDs for layout resources.
     */
    public static final class layout {
        /**
         * Resource ID for the main layout.
         */
        public static final int main = 0x7f030000;
    }

    /**
     * The {@code string} class contains resource IDs for string resources.
     */
    public static final class string {
        /**
         * Resource ID for the application name string.
         */
        public static final int app_name = 0x7f040001;
        
        /**
         * Resource ID for the first string.
         */
        public static final int first = 0x7f040002;
        
        /**
         * Resource ID for the hello string.
         */
        public static final int hello = 0x7f040000;
        
        /**
         * Resource ID for the second string.
         */
        public static final int second = 0x7f040003;
    }
}
