package com.uc.paymentsdk.util.Constants;
import java.lang.String;
import android.graphics.Color;
import java.lang.Math;
import java.lang.Object;

public class Constants	// class@0000bc from classes.dex
{
    public static final int ACTION_ARRIVE_PAY_POINT = 9;
    public static final int ACTION_CHARGE_PHONECARD = 10;
    public static final int ACTION_CHECK_USERNAME = 2;
    public static final int ACTION_CONFIRM_PAY_RESULT = 5;
    public static final int ACTION_LOGIN = 0;
    public static final int ACTION_PAY = 3;
    public static final int ACTION_PAY_PAYPASS = 4;
    public static final int ACTION_POST_SMS_PAYMENT = 8;
    public static final int ACTION_QUERY_CHARGE_CHANNEL = 17;
    public static final int ACTION_QUERY_CHARGE_PHONECARD_RESULT = 12;
    public static final int ACTION_QUERY_PAY_CHANNEL = 6;
    public static final int ACTION_QUERY_UPOINT_DISCOUNT = 18;
    public static final int ACTION_REGISTER = 1;
    public static final int ACTION_SYNC_CARD_INFO = 11;
    public static final int ACTION_SYNC_SMS_INFO = 7;
    public static final String[] API_URLS;
    public static final String APPKEY;
    public static final int CHARGEMENT_DEFAULT;
    public static final int CHARGE_ALIPAY_INPUT_LENGTH_MAX;
    public static final int CHARGE_G_INPUT_LENGTH_MAX;
    public static final long CHARGE_QUERY_RESULT_TIME;
    public static final String CODE_KEY_PAY_AND_ACCOUNT;
    public static final int COLOR_CHARGE_CHANGE_TYPE;
    public static final int COLOR_ERROR_BACKGROUND;
    public static final int COLOR_LINK_TEXT;
    public static final int COLOR_LISTVIEW_ITEM_BACKGROUND;
    public static final int COLOR_PRESSED;
    public static final int COLOR_SUBTITLE_BACKGROUND1;
    public static final int COLOR_SUBTITLE_BACKGROUND2;
    public static final int COLOR_TITLE_BACKGROUND;
    public static final String CPID;
    public static final String CPID_PATTERN;
    public static final int CUSTOM_TEXTVIEW_HEIGHT;
    public static final int CUSTOM_TEXTVIEW_HEIGHT_HDPI;
    public static final boolean DEBUG;
    public static final String EMAIL_ADDRESS_PATTERN;
    public static final String ERROR_ACCOUNT_APPKEY_WRONG;
    public static final String ERROR_ACCOUNT_ARG_OUT_OF_SCROPE;
    public static final String ERROR_ACCOUNT_CHANEL_NOT_EXIST;
    public static final String ERROR_ACCOUNT_EMAIL_HAVE_EXIST;
    public static final String ERROR_ACCOUNT_EMAIL_WRONG_FORMAT;
    public static final String ERROR_ACCOUNT_NETWORK;
    public static final String ERROR_ACCOUNT_PARSER;
    public static final String ERROR_ACCOUNT_PASSWORD;
    public static final String ERROR_ACCOUNT_PASSWORD_INVALIDATE;
    public static final String ERROR_ACCOUNT_REQUEST_DECODE_FAILED;
    public static final String ERROR_ACCOUNT_UNKNOWN;
    public static final String ERROR_ACCOUNT_USERAGENT_PARAM_EMPTY;
    public static final String ERROR_ACCOUNT_USERNAME_HAVE_EXIST;
    public static final String ERROR_ACCOUNT_USERNAME_INVALIDATE;
    public static final String ERROR_ACCOUNT_USERNAME_NOT_EXIST;
    public static final String ERROR_ACCOUNT_XML_PARSE_FAILED;
    public static final String ERROR_ACCOUNT_XML_PARSE_FAILED2;
    public static final int ERROR_CODE_APPKEY_WRONG;
    public static final int ERROR_CODE_ARG_OUT_OF_SCROPE;
    public static final int ERROR_CODE_CHANEL_NOT_EXIST;
    public static final int ERROR_CODE_EMAIL_HAVE_EXIST;
    public static final int ERROR_CODE_EMAIL_WRONG_FORMAT;
    public static final int ERROR_CODE_INSUFFICIENT_BALANCE;
    public static final int ERROR_CODE_NETWORK;
    public static final int ERROR_CODE_PARSER;
    public static final int ERROR_CODE_PASSWORD_INVALIDATE;
    public static final int ERROR_CODE_PASSWORD_WRONG;
    public static final int ERROR_CODE_PAY_FAILED;
    public static final int ERROR_CODE_REQUEST_DECODE_FAILED;
    public static final int ERROR_CODE_UNKNOWN;
    public static final int ERROR_CODE_USERAGENT_PARAM_EMPTY;
    public static final int ERROR_CODE_USERNAME_HAVE_EXIST;
    public static final int ERROR_CODE_USERNAME_INVALIDATE;
    public static final int ERROR_CODE_USERNAME_NOT_EXIST;
    public static final int ERROR_CODE_XML_PARSE_FAILED;
    public static final int ERROR_CODE_XML_PARSE_FAILED2;
    public static final String ERROR_INVALID_ACCOUNT;
    public static final String ERROR_NETWORK_FAILED;
    public static final String ERROR_PASSWORD_IS_EMPTY;
    public static final String ERROR_PASSWORD_OR_USERNAME_IS_EMPTY;
    public static final String ERROR_REGISTER_EMAIL_IS_EMPTY;
    public static final String ERROR_REGISTER_EMAIL_IS_WRONG;
    public static final String ERROR_REGISTER_PASSWORD2_WRONG;
    public static final String ERROR_REGISTER_PASSWORD_AND_PASSWORD_WRONG;
    public static final String ERROR_REGISTER_PASSWORD_WRONG;
    public static final String ERROR_REGISTER_UNSERNAME_WRONG2;
    public static final String ERROR_REGISTER_USERNAME_NOT_ALL_NUMBER;
    public static final String ERROR_REGISTER_USERNAME_NOT_EMAIL;
    public static final String ERROR_REGISTER_USERNAME_WRONG;
    public static final String ERROR_START_APPKEY_INVALID;
    public static final String ERROR_START_CPID_INVALID;
    public static final int ERROR_TIMEOUT;
    public static final String ERROR_TITLE;
    public static final String ERROR_TYPE_NOT_SUPPORTED;
    public static final int ERROR_UNKNOWN;
    public static final String ERROR_USERNAME_IS_EMPTY;
    public static final String EXTRA_ERROR;
    public static final String EXTRA_FROM_CHARGE;
    public static final String EXTRA_G_BALANCE;
    public static final String EXTRA_JIFENGQUAN_BALANCE;
    public static final String GET;
    public static final String HOST;
    public static final String HOST_PAY;
    public static final int JIFENGQUAN_G_RATIO;
    public static final int PAYMENT_DESC_LENGTH_MAX;
    public static final int PAYMENT_JIFENGQUAN_MAX;
    public static final int PAYMENT_JIFENGQUAN_MIN;
    public static final int PAYMENT_MAX;
    public static final int PAYMENT_MIN;
    public static final int PAYMENT_NAME_LENGTH_MAX;
    public static final int PAYMENT_SMS_PAYNAME_BYTE_LENGTH_MAX;
    public static final String POST;
    public static final int REGIST_NAME_MAX_LENGTH;
    public static final int REGIST_NAME_MIN_LENGTH;
    public static final int RENMINBI_JIFENGQUAN_RATIO;
    public static final int RENMINBI_SMS_RATIO;
    public static final String RES_ALIPAY;
    public static final String RES_ALIPAY_HDPI;
    public static final String RES_ALIPAY_PLUGIN_APK;
    public static final String RES_LIST_ITEM_MORE_ICON;
    public static final String RES_LOCK;
    public static final String RES_LOCK_HDPI;
    public static final String RES_TYPE_ALIPAY_ICON;
    public static final String RES_TYPE_ALIPAY_ICON_HDPI;
    public static final String RES_TYPE_GFAN_ICON;
    public static final String RES_TYPE_GFAN_ICON_HDPI;
    public static final String RES_TYPE_G_ICON;
    public static final String RES_TYPE_G_ICON_HDPI;
    public static final String RES_TYPE_PHONECARD_ICON;
    public static final String RES_TYPE_PHONECARD_ICON_HDPI;
    public static final String RES_TYPE_SMS_ICON;
    public static final String RES_TYPE_SMS_ICON_HDPI;
    public static final String SMS_INFO_BEFORE_SEND_BEIWEI;
    public static final String SMS_SUCCESS;
    public static final String TERM;
    public static final String TEXT_BACK_TO_PAY;
    public static final String TEXT_BACK_TO_PAYPOINT;
    public static final int TEXT_CHARGE_TITLE_LENGTH_MAX;
    public static final String TEXT_CONFIRM_TO_CANCEL;
    public static final String TEXT_DELETE;
    public static final String TEXT_EXIT;
    public static final String TEXT_INSUFFENT_BALANCE;
    public static final String TEXT_INSUFFENT_BALANCE2;
    public static final String TEXT_NOT_DELETE;
    public static final String TEXT_PAY_SMS_BACK_CONFIRM;
    public static final String TEXT_PAY_SMS_CHANCEL_CONFIRM;
    public static final String TEXT_PAY_SMS_CONFIRM_INDEXOF;
    public static final String TEXT_PAY_SMS_CONFRIM_RESULT_CONTAIN;
    public static final String TEXT_PAY_SMS_CONFRIM_START_WITH;
    public static final String TEXT_PAY_SMS_CONFRIM_SUPPORTTEL_START_WITH;
    public static final String TEXT_PAY_SMS_DELETE_BACK_CONFIRM;
    public static final String TEXT_PAY_SMS_DELETE_CONFIRM;
    public static final String TEXT_PAY_SMS_FAILED;
    public static final String TEXT_PAY_SMS_FAILED_INSUFFENT_BALANCE;
    public static final int TEXT_SIZE;
    public static final String VERSION;

    static {
       String[] stringArray = new String[19];
       stringArray[0] = "http://g2.uc.cn/ucgame/charge/login";
       stringArray[1] = "http://g2.uc.cn/ucgame/charge/register";
       stringArray[2] = "http://g2.uc.cn/ucgame/charge/check_username";
       stringArray[3] = "http://g2.uc.cn/ucgame/charge/charge_umoney";
       stringArray[4] = "http://g2.uc.cn/ucgame/charge/charge_umoney";
       stringArray[5] = "http://g2.uc.cn/ucgame/charge/sdkConfirm";
       stringArray[6] = "http://g2.uc.cn/ucgame/charge/getPayType";
       stringArray[7] = "http://g2.uc.cn/ucgame/charge/update_sms";
       stringArray[8] = "http://g2.uc.cn/ucgame/charge/getClientMessagePay";
       stringArray[9] = "http://g2.uc.cn/ucgame/charge/sdkPayPointArrive";
       stringArray[10] = "http://g2.uc.cn/ucgame/charge/rechargeRequest";
       stringArray[11] = "http://g2.uc.cn/ucgame/charge/getCardConfigServlet";
       stringArray[12] = "http://g2.uc.cn/ucgame/charge/queryServlet";
       stringArray[13] = "http://g2.uc.cn/ucgame/charge/businessProcess.do";
       stringArray[14] = "http://g2.uc.cn/ucgame/charge/businessProcess.do";
       stringArray[15] = "http://g2.uc.cn/ucgame/charge/businessProcess.do";
       stringArray[16] = "http://g2.uc.cn/ucgame/charge/businessProcess.do";
       stringArray[17] = "http://g2.uc.cn/ucgame/charge/businessProcess";
       stringArray[18] = "http://g2.uc.cn/ucgame/charge/gain_discount";
       Constants.API_URLS = stringArray;
       Constants.COLOR_TITLE_BACKGROUND = Color.parseColor("#FF8B4B3C");
       Constants.COLOR_SUBTITLE_BACKGROUND1 = Color.parseColor("#FFFFB546");
       Constants.COLOR_SUBTITLE_BACKGROUND2 = Color.parseColor("#FFFF6633");
       Constants.CHARGE_ALIPAY_INPUT_LENGTH_MAX = (int)Math.log10(10000.00f);
       Constants.CHARGE_G_INPUT_LENGTH_MAX = Constants.CHARGE_ALIPAY_INPUT_LENGTH_MAX + 1;
    }
    public void Constants(){
       super();
    }
}
